# Generated by Django 5.0.6 on 2024-05-21 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FanSpecification',
            fields=[
                ('speed_level', models.IntegerField(primary_key=True, serialize=False)),
                ('current', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('speed_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fan_app.fanspecification')),
            ],
        ),
    ]
